do not export JMX_PORT to configure default port
using KAFKA_JMX_PORT to prevent conflict

precludes running scripts that call kafka-run-class.sh within the
running container resulting in an exception (process spawned from
kafka-start-server.sh already bound to the port defined)

Error: Exception thrown by the agent : java.rmi.server.ExportException:
Port already in use: 7203; nested exception is:
  java.net.BindException: Address already in use